// Barrel re-exports — grouped by category
export { NavbarBlock } from './layout/navbar-block'
export { FooterBlock } from './layout/footer-block'
export { MenuBlock } from './layout/menu-block'
export { TubelightNavbarBlock } from './layout/tubelight-navbar-block'
export { AnnouncementBar } from './layout/announcement-bar'

export { ScrollExpandHero } from './visual/scroll-expand-hero'
export { GlowingShadow } from './visual/glowing-shadow'
export { GlowButton, ShinyButtonBlock } from './visual/shiny-button'
export { PromotionsBanner } from './visual/promotions-banner'

export { FeaturedProductsGrid } from './commerce/featured-products-grid'
export { CategoryGrid } from './commerce/category-grid'
export { CouponSpotlight } from './commerce/coupon-spotlight'
export { TrustStrip } from './commerce/trust-strip'
export { ProductRangeTable } from './commerce/product-range-table'
export { LoyaltyWidgetSection } from './commerce/loyalty-widget-section'

export { TestimonialsCarousel } from './content/testimonials-carousel'
export { NewsletterSection } from './content/newsletter-section'
export { CTABanner } from './content/cta-banner'
export { DualCtaBanner } from './content/dual-cta-banner'
export { StatsBand } from './content/stats-band'
export { HowToOrder } from './content/how-to-order'
export { ButtonGroup } from './content/button-group'
