"""add_contact_plugin_and_trade_fields

Revision ID: 5a874f25caca
Revises: f3e2d1c0b9a8
Create Date: 2026-06-16 01:32:08.627107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a874f25caca'
down_revision: Union[str, None] = 'f3e2d1c0b9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    existing = {row[0] for row in conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table'"))}

    if 'enquiries' not in existing:
        op.create_table('enquiries',
        sa.Column('enquiry_type', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('company', sa.String(length=255), nullable=True),
        sa.Column('subject', sa.String(length=200), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('material_type', sa.String(length=200), nullable=True),
        sa.Column('quantity_description', sa.String(length=500), nullable=True),
        sa.Column('size_spec', sa.String(length=500), nullable=True),
        sa.Column('deadline', sa.String(length=100), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    coupon_cols = {row[1] for row in conn.execute(sa.text("PRAGMA table_info(coupons)"))}
    if 'show_on_homepage' not in coupon_cols:
        op.add_column('coupons', sa.Column('show_on_homepage', sa.Boolean(), nullable=False, server_default='0'))

    user_cols = {row[1] for row in conn.execute(sa.text("PRAGMA table_info(users)"))}
    if 'vat_number' not in user_cols:
        op.add_column('users', sa.Column('vat_number', sa.String(length=50), nullable=True))
    if 'business_type' not in user_cols:
        op.add_column('users', sa.Column('business_type', sa.String(length=100), nullable=True))
    if 'trade_status' not in user_cols:
        op.add_column('users', sa.Column('trade_status', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trade_status')
    op.drop_column('users', 'business_type')
    op.drop_column('users', 'vat_number')
    op.drop_column('coupons', 'show_on_homepage')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
