"""add_email_verification_to_users

Revision ID: 90394a6d235f
Revises: 5a874f25caca
Create Date: 2026-06-16 01:52:59.460292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90394a6d235f'
down_revision: Union[str, None] = '5a874f25caca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###
