"""add_order_fulfillment_fields

Revision ID: a35a00f107db
Revises: 90394a6d235f
Create Date: 2026-06-16 02:00:59.791218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a35a00f107db'
down_revision: Union[str, None] = '90394a6d235f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
